#!/bin/sh

set -eux

createdb -U postgres omdb

psql -v ON_ERROR_STOP=1 -X omdb -U postgres <<EOF
SET ROLE postgres;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS tsm_system_rows;
\i omdb.sql
EOF
